# Generated by Django 4.0.5 on 2022-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortt',
            name='shortcode',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
