# Generated by Django 4.0.5 on 2022-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortt_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortt',
            name='shortcode',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
