# Generated by Django 4.0.5 on 2022-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortt_active_alter_shortt_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortt',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
