# Generated by Django 4.0.5 on 2022-07-16 14:52

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_shortt_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortt',
            name='url',
            field=models.CharField(max_length=255, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
