# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Heroku Build
      # You may pin to the exact commit or the version.
      # uses: behe/heroku-build@d1420cf172bb918aae4f0081b1c3fba69e1659ad
      uses: behe/heroku-build@v1.1
      with:
        # Name of Heroku application
        app-name: 'diminutive'
        # API key with the deploy role
        api-key: ${{secrets.HEROKU_API_KEY}}
        # Directory to upload
        #path: # optional, default is .
